# =============================================================================
# Noti Service Only
# =============================================================================
# This docker-compose file is for local development when core-platform
# infrastructure (MySQL, Eureka) is already running
# =============================================================================

services:
  noti-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/asyncsite/noti-service:latest
    container_name: asyncsite-noti-service
    restart: unless-stopped
    ports:
      - "8089:8089"
    environment:
      # Spring Configuration
      - SPRING_PROFILES_ACTIVE=docker,microservices
      # Service Discovery (uses shared Eureka)
      - EUREKA_CLIENT_ENABLED=true
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://asyncsite-eureka:8761/eureka/
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - EUREKA_INSTANCE_INSTANCE_ID=noti-service:8089
      - EUREKA_INSTANCE_METADATA_MAP_VERSION=1.0.0
      - EUREKA_INSTANCE_METADATA_MAP_ZONE=docker
      # Database Configuration (uses shared MySQL)
      - SPRING_DATASOURCE_URL=jdbc:mysql://asyncsite-mysql:3306/notidb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&characterEncoding=utf8&useUnicode=true&createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=asyncsite_root_2024!
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      # JPA/Hibernate Configuration
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=false
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQLDialect
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=false
      # Mail Configuration
      - SPRING_MAIL_HOST=smtp.gmail.com
      - SPRING_MAIL_PORT=587
      - SPRING_MAIL_USERNAME=asyncsite@gmail.com
      - SPRING_MAIL_PASSWORD=unkhpoegvshusagl
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=true
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=true
      # Application Configuration
      - APPLICATION_NOTIFICATION_EMAIL_ENABLED=true
      - APPLICATION_NOTIFICATION_EMAIL_FROM_ADDRESS=asyncsite@gmail.com
      - APPLICATION_NOTIFICATION_EMAIL_RETRY_ATTEMPTS=3
      - APPLICATION_NOTIFICATION_EMAIL_RETRY_DELAY=5000
      - APPLICATION_NOTIFICATION_DISCORD_ENABLED=true
      - APPLICATION_NOTIFICATION_DISCORD_WEBHOOK_URL=
      - APPLICATION_NOTIFICATION_DISCORD_RETRY_ATTEMPTS=3
      - APPLICATION_NOTIFICATION_DISCORD_RETRY_DELAY=3000
      # Async Configuration
      - APPLICATION_NOTIFICATION_ASYNC_CORE_POOL_SIZE=5
      - APPLICATION_NOTIFICATION_ASYNC_MAX_POOL_SIZE=10
      - APPLICATION_NOTIFICATION_ASYNC_QUEUE_CAPACITY=100
      - APPLICATION_NOTIFICATION_ASYNC_THREAD_NAME_PREFIX=noti-async-
      # Logging Configuration
      - LOGGING_LEVEL_COM_ASYNCSITE_NOTISERVICE=INFO
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB=INFO
      - LOGGING_LEVEL_ORG_HIBERNATE_SQL=WARN
      # Management and Health
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=health,info,metrics,prometheus
      - MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS=always
      - MANAGEMENT_HEALTH_DB_ENABLED=true
    volumes:
      - noti-service-logs:/app/logs
    networks:
      - asyncsite-network
    logging: # 저트래픽 설정 적용
      driver: "json-file"
      options:
        max-size: "30m"
        max-file: "3"
    # Health check configuration
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8089/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 768M
          cpus: '1.0'
        reservations:
          memory: 384M
          cpus: '0.5'
    # Labels for service identification
    labels:
      - "com.asyncsite.service=noti-service"
      - "com.asyncsite.tier=business"
      - "com.asyncsite.type=microservice"
      - "com.asyncsite.domain=notification"

# =============================================================================
# Network and Volume Configuration
# =============================================================================
networks:
  default:
    external: true
    name: asyncsite-network

volumes:
  noti-service-logs:
    driver: local