# =============================================================================
# Noti Service - Complete Stack
# =============================================================================
# This docker-compose file contains:
# - Shared Infrastructure: MySQL, Eureka
# - Noti Service: Notification Management and Delivery
# 
# Infrastructure services use consistent container names across all services.
# Docker automatically prevents duplicate containers with the same name.
# =============================================================================

services:
  # =============================================================================
  # Shared Infrastructure Services
  # These services are shared across all microservices in the asyncsite ecosystem
  # =============================================================================
  
  # MySQL - Main Database
  mysql:
    image: mysql:8.0
    container_name: asyncsite-mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: asyncsite_root_2024!
    volumes:
      - asyncsite-mysql-data:/var/lib/mysql
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/init:/docker-entrypoint-initdb.d
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'
    labels:
      - "com.asyncsite.service=mysql"
      - "com.asyncsite.tier=data"
      - "com.asyncsite.type=infrastructure"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Eureka Server - Service Discovery
  eureka:
    image: asyncsite/eureka:latest
    container_name: asyncsite-eureka
    restart: unless-stopped
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    labels:
      - "com.asyncsite.service=eureka"
      - "com.asyncsite.tier=platform"
      - "com.asyncsite.type=infrastructure"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8761/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # =============================================================================
  # Noti Service - Notification Management and Delivery
  # =============================================================================
  # Handles notification templates, channels, settings, and delivery
  noti-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/asyncsite/noti-service:latest
    container_name: asyncsite-noti-service
    restart: unless-stopped
    ports:
      - "8084:8084"
    environment:
      # Spring Configuration
      - SPRING_PROFILES_ACTIVE=docker,microservices
      # Service Discovery (uses shared Eureka)
      - EUREKA_CLIENT_ENABLED=true
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://asyncsite-eureka:8761/eureka/
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - EUREKA_INSTANCE_INSTANCE_ID=${HOSTNAME}:noti-service:8084
      - EUREKA_INSTANCE_METADATA_MAP_VERSION=1.0.0
      - EUREKA_INSTANCE_METADATA_MAP_ZONE=docker
      # Database Configuration (uses shared MySQL)
      - SPRING_DATASOURCE_URL=jdbc:mysql://asyncsite-mysql:3306/notidb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&characterEncoding=utf8&useUnicode=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=asyncsite_root_2024!
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      # JPA/Hibernate Configuration
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=false
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQLDialect
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=false
      # Mail Configuration
      - SPRING_MAIL_HOST=${MAIL_HOST:smtp.gmail.com}
      - SPRING_MAIL_PORT=${MAIL_PORT:587}
      - SPRING_MAIL_USERNAME=${MAIL_USERNAME:}
      - SPRING_MAIL_PASSWORD=${MAIL_PASSWORD:}
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=true
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=true
      # Application Configuration
      - APPLICATION_NOTIFICATION_EMAIL_ENABLED=true
      - APPLICATION_NOTIFICATION_EMAIL_FROM_ADDRESS=${MAIL_FROM:noreply@asyncsite.com}
      - APPLICATION_NOTIFICATION_EMAIL_RETRY_ATTEMPTS=3
      - APPLICATION_NOTIFICATION_EMAIL_RETRY_DELAY=5000
      - APPLICATION_NOTIFICATION_DISCORD_ENABLED=true
      - APPLICATION_NOTIFICATION_DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL:}
      - APPLICATION_NOTIFICATION_DISCORD_RETRY_ATTEMPTS=3
      - APPLICATION_NOTIFICATION_DISCORD_RETRY_DELAY=3000
      # Async Configuration
      - APPLICATION_NOTIFICATION_ASYNC_CORE_POOL_SIZE=5
      - APPLICATION_NOTIFICATION_ASYNC_MAX_POOL_SIZE=10
      - APPLICATION_NOTIFICATION_ASYNC_QUEUE_CAPACITY=100
      - APPLICATION_NOTIFICATION_ASYNC_THREAD_NAME_PREFIX=noti-async-
      # Logging Configuration
      - LOGGING_LEVEL_COM_ASYNCSITE_NOTISERVICE=INFO
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB=INFO
      - LOGGING_LEVEL_ORG_HIBERNATE_SQL=WARN
      # Management and Health
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=health,info,metrics,prometheus
      - MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS=always
      - MANAGEMENT_HEALTH_DB_ENABLED=true
    volumes:
      - noti-service-logs:/app/logs
    networks:
      - asyncsite-network
    depends_on:
      - mysql
      - eureka
    # Health check configuration
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8084/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 768M
          cpus: '1.0'
        reservations:
          memory: 384M
          cpus: '0.5'
    # Labels for service identification
    labels:
      - "com.asyncsite.service=noti-service"
      - "com.asyncsite.tier=business"
      - "com.asyncsite.type=microservice"
      - "com.asyncsite.domain=notification"

# =============================================================================
# Network and Volume Configuration
# =============================================================================
networks:
  default:
    external: true
    name: asyncsite-network

volumes:
  asyncsite-mysql-data:
    external: true
  noti-service-logs:
    driver: local