spring:
  datasource:
    url: jdbc:h2:mem:notitestdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

server:
  port: 0

# Disable Eureka for tests
eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false

# Disable mail for tests
spring.mail:
  host: localhost
  port: 1025
  
# Application configuration for tests
application:
  notification:
    email:
      enabled: false
    discord:
      enabled: false

logging:
  level:
    com.asyncsite: DEBUG
    com.asyncsite.notiservice.config: DEBUG
    org.springframework.web: WARN
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
